In [2]:
from dataset import CustomDataset, MultiEpochsDataLoader
import numpy as np
import torch
from torch.utils.data import DataLoader
from tqdm.notebook import tqdm

In [2]:
# See if MultiEpochsDataLoader is faster than normal pytorch dataloader
len = 1000
a = np.random.rand(len, 3).astype(np.float32)
a[:, 0] = np.arange(len).astype(np.float32)
b = np.rint(np.random.rand(len))
c = np.rint(np.random.rand(len))

dataset = CustomDataset(a, b, c)
d1 = DataLoader(dataset, batch_size=256, shuffle=True, num_workers=4, pin_memory=True, persistent_workers=True)
d2 = MultiEpochsDataLoader(dataset, batch_size=256, shuffle=True, num_workers=4, pin_memory=True, persistent_workers=True)

for _ in tqdm(range(10)):
    for __ in range(10):
        for ___ in range(500):
            for batch in d2:
                pass

for _ in tqdm(range(10)):
    for __ in range(10):
        for ___ in range(500):
            for batch in d1:
                pass

  0%|          | 0/10 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

In [3]:
# Check if MultiEpochsDataLoader shuffles data

len = 10
a = np.random.rand(len, 3).astype(np.float32)
a[:, 0] = np.arange(len).astype(np.float32)
b = np.rint(np.random.rand(len))
c = np.rint(np.random.rand(len))

dataset = CustomDataset(a, b, c)
d = MultiEpochsDataLoader(dataset, batch_size=2, shuffle=True, num_workers=4, pin_memory=True, persistent_workers=True)

r1 = []
r2 = []
for e in range(2):
    for batch in d:
        if e == 0:
            r1.append(batch)
        else:
            r2.append(batch)

for batch in r1:
    print(batch)
print("__________________________")
for batch in r2:
    print(batch)

[tensor([[4.0000, 0.3833, 0.1364],
        [6.0000, 0.3211, 0.7636]]), tensor([1, 0]), tensor([1, 0])]
[tensor([[8.0000, 0.1532, 0.0182],
        [9.0000, 0.2500, 0.5472]]), tensor([0, 0]), tensor([1, 1])]
[tensor([[7.0000e+00, 4.4640e-03, 4.1253e-01],
        [5.0000e+00, 1.4409e-01, 8.3813e-01]]), tensor([0, 1]), tensor([0, 1])]
[tensor([[2.0000, 0.0451, 0.7399],
        [1.0000, 0.8743, 0.2458]]), tensor([1, 0]), tensor([1, 0])]
[tensor([[3.0000, 0.4744, 0.5670],
        [0.0000, 0.7924, 0.7799]]), tensor([1, 1]), tensor([0, 0])]
__________________________
[tensor([[1.0000, 0.8743, 0.2458],
        [0.0000, 0.7924, 0.7799]]), tensor([0, 1]), tensor([0, 0])]
[tensor([[8.0000, 0.1532, 0.0182],
        [2.0000, 0.0451, 0.7399]]), tensor([0, 1]), tensor([1, 1])]
[tensor([[7.0000e+00, 4.4640e-03, 4.1253e-01],
        [9.0000e+00, 2.5000e-01, 5.4719e-01]]), tensor([0, 0]), tensor([0, 1])]
[tensor([[5.0000, 0.1441, 0.8381],
        [6.0000, 0.3211, 0.7636]]), tensor([1, 0]), tensor([1, 0])

In [4]:
# Check if MultiEpochsDataLoader gives all samples as inputs
len = 10
a = np.random.rand(len, 3).astype(np.float32)
a[:, 0] = np.arange(len).astype(np.float32)
b = np.rint(np.random.rand(len))
c = np.rint(np.random.rand(len))
count = [0 for _ in range(len)]

dataset = CustomDataset(a, b, c)
d = MultiEpochsDataLoader(dataset, batch_size=2, shuffle=True, num_workers=3, pin_memory=True, persistent_workers=True)

print(count)
for _ in range(100):
    for batch in d:
        for idx in batch[0][:, 0]:
            count[int(idx)] += 1
print(count)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[100, 100, 100, 100, 100, 100, 100, 100, 100, 100]


In [13]:
np.random.seed(42)
def t(a: np.ndarray):
    b = a.copy()
    np.random.shuffle(b)
    print(b)

a = np.arange(10)
print(a)
t(a)
print(a)
t(a)
print(a)
t(a)

[0 1 2 3 4 5 6 7 8 9]
[8 1 5 0 7 2 9 4 3 6]
[0 1 2 3 4 5 6 7 8 9]
[0 1 8 5 3 4 7 9 6 2]
[0 1 2 3 4 5 6 7 8 9]
[9 2 0 6 8 5 3 7 1 4]


In [3]:
a = torch.empty(0)
b = torch.ones(16)
print(a)
print(b)
print(torch.concat((a, b)))

tensor([])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [ ]:
import numpy as np
l = 0.21875
h = 0.40625
a = "["
for c in np.linspace(l, h, 21):
    a+= f"{c:f}, "
a = a[:-2]
a += "]"
print(a)